### PR TITLE
Assorted store fixes

### LINKED ISSUE #152: Chain MMR and note consumption
This is a tricky problem, found by @igamigo while working on the client. I'm going try to lay down the problems:

1. A block's MMR does not include itself, this is because
  a. The MMR is build with blocks as leaves
  b. Self reference does not work with hashing
2. A note must be at least 1 block old for it to be consumed, this is because:
  a. To consume a note, an inclusion proof is required
  b. The inclusion proof is done against the MMR
  c. Because of 2.b. and 1. a transaction consuming a note can not use its creation block as a reference
3. A note returned in a `sync` request can not be consumed without a subsequent request, this is because:
  a. The request return block which produces a note of interested
  b. Because of 2. this note can not be consumed and a new request to fetch a new block is necessary
4. A block returned by `sync` can not be tracked, this is because
  a. The PartialMMR requires a valid merkle path to track an item
  b. Because of 2. to run a transaction the block's MMR must be known, so that is returned by `sync`
  c. Because of 1. 4.a and 4.b the block can not be tracked

### PR DESCRIPTION
**Pull request by bobbinth**
This PR extracts store-related fixes from #155 which close #152 and also make sure `apply_block` request succeeds on the store.

### CODE REVIEW

File: store/src/state.rs [hunk 1]
```diff
@@ -355,10 +356,9 @@ impl State {
                 .chain_mmr
                 .get_delta(block_num as usize, state_sync.block_header.block_num as usize)?;
 
-            let proof = inner.chain_mmr.open(
-                state_sync.block_header.block_num as usize,
-                state_sync.block_header.block_num as usize + 1,
-            )?;
+            let proof = inner
+                .chain_mmr
+                .open(block_num as usize, state_sync.block_header.block_num as usize)?;
```
Comment (hackaugusto) [inline store/src/state.rs:361]: The merkle path shouldn't be necessary. The client can just add the last block as a new peak, and track it. All the information needed is available:

- on a new update: the left siblings of the merkle path are the existing mmr peaks, the right siblings are from the new delta.
- on the add mentioned above: explained here https://github.com/0xPolygonMiden/miden-node/issues/152#issuecomment-1894597087
