### PR TITLE
Fix config file and remove defaults

### LINKED ISSUE #113: Config file naming and defaults
In #110 we implemented a single config file which currently looks like this:
```Toml
[block_producer]
host_port = { host = "127.0.0.1", port = 8080 }
store_endpoint = "http://store:8000"

[rpc]
host_port = { host = "127.0.0.1", port = 8080 }
store_endpoint = "http://store:8000"
block_producer_endpoint = "http://block_producer:8001"

[store]
host_port = { host = "127.0.0.1", port = 8080 }
sqlite = "local.sqlite3"
genesis_filepath = "genesis.dat"
```

I think something more like this would be more intuitive:
```Toml
[block_producer]
endpoint = { host = "127.0.0.1", port = 8080 }
store_url = "http://store:8000"
     
[rpc]
endpoint = { host = "127.0.0.1", port = 8080 }
store_url = "http://store:8000"
block_producer_url = "http://block_producer:8001"

[store]
endpoint = { host = "127.0.0.1", port = 8080 }
database_filepath = "local.sqlite3"
genesis_filepath = "genesis.dat"
```

The main differences are:
- Instead of `host_port` we'd use `endpoint`. I think it is better than `host_port`, but I don't love `endpoint` either. Other options could be `server`, `binding`, or maybe something else.
- For upstream components we'd use `_url` rather than `_endpoint`. I think it differentiates these a bit better from the `endpoint`.
- Instead of `store.sqlite` we'd use `store.database_filepath`. Another option is to use just `store.database`. This would keep it a bit more flexible in case we use a different database (e.g., Postgres).

### Defaults
I'd prefer to use the defaults as sparsely as possible. I think making things explicit avoids confusion down the road.

So, maybe the only default that we need is the config file path when we start the server. I think the default there could be `miden.toml`. So, the following would be equivalent:

```
miden-node start
miden-node start --config miden.toml
```
Everything else would be provided via the config file (and maybe environment variables - though, this too could create confusion).

### PR DESCRIPTION
**Pull request by plafer**
Closes #113

### CODE REVIEW

**Comment by plafer** [comment]
@bobbinth ready for review! A few notes:

- I left the environment variable functionality
- Removed all default functionality - everything must be derived from the config file (or env vars).
  - I currently left some remnants of the default functionality, such as [`Config` requiring `Default`](https://github.com/0xPolygonMiden/miden-node/blob/80c805094a3fe39f0c81d916ea04f8bdd7e78b26/utils/src/config.rs#L25), and unused `Default` values for the configs (e.g. [`StoreConfig`](https://github.com/0xPolygonMiden/miden-node/blob/80c805094a3fe39f0c81d916ea04f8bdd7e78b26/store/src/config.rs#L41-L50)). Should we completely remove all that?
- `miden-node make-genesis` now generates everything in the current directory by default (as opposed to at e.g. `~/Library/Application Support/Polygon.Miden/genesis.dat`)
- I added a `miden-node-example.toml` example config in `node/src`. I was thinking to add similar ones for the other executables with https://github.com/0xPolygonMiden/miden-node/issues/111

File: rpc/src/main.rs [hunk 1]
```diff
@@ -24,7 +24,7 @@ async fn main() -> Result<()> {
         Command::Request(req) => match req {
             Request::CheckNullifiers { nullifiers } => {
                 let host_port =
-                    format!("http://{}:{}", config.rpc.host_port.host, config.rpc.host_port.port);
+                    format!("http://{}:{}", config.rpc.endpoint.host, config.rpc.endpoint.port);
```
Comment (bobbinth) [inline rpc/src/main.rs:27]: Should we rename the variable here as well from `host_port` to something else?

File: node/src/config.rs
Comment (bobbinth) [inline node/src/config.rs:1]: Should `CONFIG_FILENAME` be set to `miden.toml`?

File: node/miden-node-example.toml [hunk 2]
```diff
@@ -0,0 +1,19 @@
+[block_producer]
+store_url = "http://localhost:28943"
+
+[block_producer.endpoint]
+host = "localhost"
+port = 48046
```
Comment (bobbinth) [inline node/miden-node-example.toml:6]: nit: I'd prefer a more compact representation - similar to what we have on line 11 below. Or at least we should be consistent.

Also, here and below, could we add comments explaining the choice of port numbers? (I think we had such comments in the code).

**Review by bobbinth — APPROVED** [review]
Looks good! Thank you! I left a few small comments inline. There are also a couple of bigger questions that you brought up:

1. Should we remove reliance on env variables? My personal opinion is that having env variables complicates things more than it helps. One potential benefit for these is when we want to provide some secret config info and we con't want to put such secrets in config files. Maybe there are others, but I'd be inclined to remove them for now and introduce them when we have a concrete use case.
2. It seems like we can't get rid of defaults completely because then we won't be able to implement `Default` on config structs. The one nice benefit of `Default` implementation is that we can use it for testing. But maybe there are good alternatives here too. And in that case, we can remove `Default` impls on configs.

File: rpc/src/main.rs (hunk 1 above)
Comment (plafer) [reply rpc/src/main.rs]: done

File: node/src/config.rs
Comment (plafer) [reply node/src/config.rs:1]: done

File: node/miden-node-example.toml (hunk 2 above)
Comment (plafer) [reply node/miden-node-example.toml]: > nit: I'd prefer a more compact representation - similar to what we have on line 11 below. Or at least we should be consistent.

> Also, here and below, could we add comments explaining the choice of port numbers? (I think we had such comments in the code).

Since this is an example file, is there actual value in how we came up with that number? IMO, any ephemeral port number would do, and whatever algorithm we used to generate it is irrelevant. Unless I'm missing something?

Comment (bobbinth) [reply node/miden-node-example.toml]: Yeah - I'm fine not including comments - though, I think it is cool info to include mostly for historical reasons.

Comment (plafer) [reply node/miden-node-example.toml]: added them - we can always remove in the future

**Comment by plafer** [comment]
@bobbinth removed all defaults, ready for review

File: utils/src/config.rs [hunk 3]
```diff
@@ -1,63 +1,29 @@
...
-        Figment::from(Serialized::defaults(Self::default()))
-            .merge(Self::load_user_config().unwrap_or_default())
-            .merge(Self::load_local_config(config_file))
-            .merge(Self::load_env_config())
-    }
+/// This function will look on the following places, from lowest to higest priority:
+///
+/// - Configuration file at the provided path. If the path is relative, searches in parent
+///   directories all the way to the root as well.
+/// - Environment variables.
```
Comment (bobbinth) [inline utils/src/config.rs:24]: Is the environment variable comment here still relevant?

**Review by bobbinth — APPROVED** [review]
Looks good! Thank you! I left one small comment inline. After it is addressed, we can merge.

File: utils/src/config.rs (hunk 3 above)
Comment (plafer) [reply utils/src/config.rs]: done

**Comment by hackaugusto** [comment]
I highly disagree with the changes done in this PR. The original configuration structure was done from a lot of experience from deploying systems to large clusters, and this is making OPSing life harder for no good reason.

1. Defaults: A server usually ends up with a few hundred configuration options. Having everything done by hand multiple times for each server because of lack of defaults is the opposite of simple, think of a user that wants to start the server to test it, why should they have to learn about metrics collection and nat punching if they just want to try it on? having the same things defined multiple times make it easier to diverge and have subtle configuration mismatches
2. Environment variables should never be used to store secrets, the environment data is persistent while a process runs, and the data can be retrieved via [unix commands](https://unix.stackexchange.com/questions/29128/how-to-read-environment-variables-of-a-process). Even if the process cleans after itself, there are attack timing vectors.
3. Environment variables have a real use case, [as I mentioned before](https://github.com/0xPolygonMiden/miden-node/pull/110#discussion_r1430634488). Lets please not ignore past comments, otherwise there is no point on trying to make them. At very least we should state that deployment is not of importance if we want to remove the feature.
4. File locations: It is super annoying when opsing having systems that don't follow proper guidelines, like storing files on the right locations, `/etc` for configs, `/usr/bin` for binaries, `/tmp` for temporary data, and so on, that is why we have [conventions](https://en.wikipedia.org/wiki/Unix_filesystem) for those, breaking these conventions just makes it harder for people to start operating the system

**Comment by bobbinth** [comment]
I don't mind adding defaults and making use of environment variables - but I think we should be careful with these as they could a double-edged sword and interplay between config files, defaults, env variables, and CLI parameters could get very confusing.

I think this also highly depends on how we see deployment process working. For example, requirements will probably differ depending on whether we expect the deployment to be done via compiling from source, pre-built binaries for various platforms, using docker images etc.

Right now, we've made the following assumptions:
- To deploy the node we need to compile it from source.
- Running the server requires `.toml` config file and all settings are in that file.
- We also needs to build a genesis file and it can also be built from a `.toml` genesis input file.

I think this is probably fine in the short term and what we want to do in the longer term deserves a separate discussion.
