### PR TITLE
fix: infinite recursion in Digest::try_into

### LINKED ISSUE #487: [Bug]: The node stops working after a transaction is sent
### Version

next

### Other packages versions

miden-client: next (more specifically on commit `2f8707faeded3725a1d732310f616e3e2170a50d`)

### What happened?

The node works correctly until a transaction from the client is sent and then it "freezes", all of the requests after that don't get a response. No error message is printed in the node console.

We noticed that after reverting the commit `[chore: update dependencies (#476)]` the node didn't have this problem. More specifically if we only revert the commit [Update tonic et al](https://github.com/0xPolygonMiden/miden-node/pull/476/commits/636c6ab1065c0bacc2bc3945eec368527936989f) the node also was suddenly fixed. It might be a problem with the new versions of prost and tonic (the client in next is also using these new versions but it seems that it doesn't cause any issues).

### What should have happened?

The node should have processed the transaction and continue responding.

### How can this be reproduced?

With a node (from branch next) running locally. Run the command `make integration-test` in from the root of the `miden-client` repo (also in branch next).

### Relevant log output

```shell
The last log printed is always the same:


2024-09-06T16:35:45.727004Z  INFO store:get_block_inputs: miden-store: crates/store/src/server/api.rs:383: new
2024-09-06T16:35:45.727019Z  INFO store:get_block_inputs:validate_nullifiers: miden-store: crates/store/src/server/api.rs:591: new
2024-09-06T16:35:45.727028Z  INFO store:get_block_inputs:validate_nullifiers: miden-store: crates/store/src/server/api.rs:591: close, time.busy: 1.42µs, time.idle: 7.83µs
2024-09-06T16:35:45.727038Z  INFO store:get_block_inputs:validate_notes: miden-store: crates/store/src/server/api.rs:601: new
2024-09-06T16:35:45.727046Z  INFO store:get_block_inputs:validate_notes: miden-store: crates/store/src/server/api.rs:601: close, time.busy: 1.04µs, time.idle: 6.62µs
2024-09-06T16:35:45.727058Z  INFO store:get_block_inputs:select_block_header_by_block_num: miden-store: crates/store/src/db/mod.rs:249: new
2024-09-06T16:35:45.727281Z  INFO store:get_block_inputs:select_block_header_by_block_num: miden-store: crates/store/src/db/mod.rs:249: close, time.busy: 22.5µs, time.idle: 201µs
2024-09-06T16:35:45.727317Z  INFO store:get_block_inputs:select_note_inclusion_proofs: miden-store: crates/store/src/db/mod.rs:370: new
2024-09-06T16:35:45.727395Z  INFO store:get_block_inputs:select_note_inclusion_proofs: miden-store: crates/store/src/db/mod.rs:370: close, time.busy: 12.6µs, time.idle: 65.4µs
2024-09-06T16:35:45.727409Z  INFO store:get_block_inputs:select_block_headers: miden-store: crates/store/src/db/mod.rs:265: new
2024-09-06T16:35:45.727493Z  INFO store:get_block_inputs:select_block_headers: miden-store: crates/store/src/db/mod.rs:265: close, time.busy: 12.3µs, time.idle: 72.2µs
2024-09-06T16:35:45.727517Z  INFO store:get_block_inputs: miden-store: crates/store/src/server/api.rs:383: close, time.busy: 191µs, time.idle: 322µs


Then it just stops responding and no more logs are printed
```

### PR DESCRIPTION
**Pull request by Mirko-von-Leipzig**
`TryFrom` implementation called `T::try_into` instead of `(*T)::try_into()` causing an infinite loop as both `T` and `&T` have this implemented.

This was introduced as part of a manual clippy fix (by me) in #476 where `x.clone().try_into()` was manually changed to `x.try_into()` instead of the suggested  `(*x).try_into()`. Does not affect any existing releases.

Fixes #487.

---------------------------

Side note: I do think implementing `TryFrom` for both owned and reference variants an anti-pattern.

### CODE REVIEW

File: crates/proto/src/domain/digest.rs [hunk 1]
```diff
@@ -187,15 +187,15 @@ impl TryFrom<&digest::Digest> for [Felt; 4] {
     type Error = ConversionError;
 
     fn try_from(value: &digest::Digest) -> Result<Self, Self::Error> {
```
Comment (bobbinth) [inline crates/proto/src/domain/digest.rs:189]: Could we alias `digest` so that this would read as something like:
```rust
fn try_from(value: &proto::Digest) -> Result<Self, Self::Error> {
```

**Review by bobbinth — APPROVED** [review]
Looks good! Thank you for tracking it down! I left one minor comment inline.

> Side note: I do think implementing `TryFrom` for both owned and reference variants an anti-pattern.

How should we change it?

**Comment by Mirko-von-Leipzig** [comment]
> Looks good! Thank you for tracking it down! I left one minor comment inline.
> 
> > Side note: I do think implementing `TryFrom` for both owned and reference variants an anti-pattern.
> 
> How should we change it?

Either

1. Only implement it for the owned variant (very rarely the reference version - only if no ownership of the data is required for some reason), or
2. named constructions/functions on the type itself

**Comment by bobbinth** [comment]
> 1. Only implement it for the owned variant (very rarely the reference version - only if no ownership of the data is required for some reason), or

If we implement it only for the owned variant, wouldn't it imply cloning in cases when we have only a reference? Or would the compiler compile this away?

**Comment by Mirko-von-Leipzig** [comment]
> > 1. Only implement it for the owned variant (very rarely the reference version - only if no ownership of the data is required for some reason), or
> 
> If we implement it only for the owned variant, wouldn't it imply cloning in cases when we have only a reference? Or would the compiler compile this away?

It depends on the implementation. If all the inner data requires cloning anyway then we shouldn't implement it for the `&T`. If some/most of the data can be taken by reference then we should only implement it for `&T`.

But maybe I'm just being overly picky because of this bug :) In this case we implemented both for a `Copy` type - and where the `&T` was internally "cloning" which isn't good. Generally we want `Clone` calls to be surfaced at the call site.
