### PR TITLE
fix(store): network notes must be public

### LINKED ISSUE #1726: Network note missing public details
Discovered on testnet v0.13.7, we appear to have a network note stored that has no public data. This causes the store query to panic which unwraps network note details since it expects them to exist:

https://github.com/0xMiden/node/blob/e44ea2bfef032d8da1c40379dae66c50c875d14b/crates/store/src/server/ntx_builder.rs#L111-L117

Example trace: https://ui.honeycomb.io/miden-e3/environments/testnet/datasets/gateway-node/result/EiEZW3y4gRC/trace/3KW7bVxBzkG?fields[]=s_name&fields[]=s_serviceName&span=c38bd3dd1c65cf3e&zoom=c38bd3dd1c65cf3e

When network notes changed to using note attachments, its now technically possible to construct a private note, and add the network note attachment to it. Which is potentially what caused this problem. We can fix this by _also_ checking that a note is public before declaring it a network note.

### PR DESCRIPTION
**Pull request by Mirko-von-Leipzig**
The counterpart of #1736 for the `next` branch.

This PR updates `miden-protocol` to include https://github.com/0xMiden/protocol/pull/2365 which added network note support. This PR then replaces our adhoc (and faulty) implementation with the one from protocol.

This does leave our types and conversions in a bit of a wonky state -- things could be cleaned up further, but since we're already actively refactoring the ntx-builder I've elected to not do this.

Fixes #1726

### CODE REVIEW

File: crates/ntx-builder/src/db/models/queries/notes.rs [hunk 1]
```diff
@@ -54,13 +55,16 @@ pub struct NoteInsert {
...
-    notes: &[SingleTargetNetworkNote],
+    notes: &[AccountTargetNetworkNote],
 ) -> Result<(), DatabaseError> {
     for note in notes {
         let row = NoteInsert {
-            nullifier: conversions::nullifier_to_bytes(&note.nullifier()),
-            account_id: conversions::network_account_id_to_bytes(note.account_id()),
-            note_data: conversions::single_target_note_to_bytes(note),
+            nullifier: conversions::nullifier_to_bytes(&note.as_note().nullifier()),
+            account_id: conversions::network_account_id_to_bytes(
```
Comment (SantiagoPittella) [inline crates/ntx-builder/src/db/models/queries/notes.rs:63]: nit: there's a bit of an inconsistency on how we are casting to bytes. In https://github.com/0xMiden/node/pull/1738/changes#diff-18f92718b4914ffa99386fe38041dec4064cde98763edefa1f8750462449af70R142 we are using:
```
            nullifier: note.as_note().nullifier().to_bytes(),
            account_id: note.target_account_id().to_bytes(),
```

Comment (Mirko-von-Leipzig) [reply crates/ntx-builder/src/db/models/queries/notes.rs:63]: I've reverted to prefer the `conversions::` functions. It would be nice to find a way to _force_ a single way of doing this. This isn't unique to this PR, or even crate, its something we'd ideally address more globally somehow.

File: crates/block-producer/src/mempool/subscription.rs [hunk 2]
```diff
@@ -83,7 +83,13 @@ impl SubscriptionProvider {
...
             .output_notes()
             .filter_map(|note| match note {
-                OutputNote::Full(inner) => NetworkNote::try_from(inner.clone()).ok(),
+                // We check first to avoid cloning non-network notes.
+                OutputNote::Full(inner) => inner.is_network_note().then_some(
+                    inner
+                        .clone()
+                        .into_account_target_network_note()
+                        .expect("we just checked that this is a network note"),
+                ),
```
Comment (igamigo) [inline crates/block-producer/src/mempool/subscription.rs:92]: @juan518munoz found an issue here where this panics. `then_some()` will imply evaluating the inner value regardless, whereas something like `then()` would do it lazily. In any case we also found that it's probably not even necessary to check for `if note.is_network_note()` because the inner conversion already implicitly checks so you can probably mtach/check for `Ok(network_note)` instead. He'll open a PR soon.

Comment (Mirko-von-Leipzig) [reply crates/block-producer/src/mempool/subscription.rs:92]: Ah of course 🤦 Thank you!
