### PR TITLE
Fix genesis block number

### LINKED ISSUE #114: Fix block numbering
While working on #107, we noticed that the current assumption is that the number of leaves in the chain MMR is equal to the latest `block_header.block_num`, and hence the genesis block's `block_num == 1`. 

We should change `block_num` to be zero-based: the number of leaves in the MMR should be equal to the latest block header's `block_num + 1`.

According to @bobbinth , this is the assumption that the transaction kernel makes.

### PR DESCRIPTION
**Pull request by plafer**
Closes #114

### CODE REVIEW

File: store/src/genesis.rs [hunk 1]
```diff
@@ -9,10 +9,12 @@ use miden_objects::{
...
 
-use crate::config::{APP, ORG};
+use crate::{
+    config::{APP, ORG},
+    state::ACCOUNT_DB_DEPTH,
+};
 
-// FIXME: This is a duplicate of the constant in `store::state`
-pub(crate) const ACCOUNT_DB_DEPTH: u8 = 64;
+pub const GENESIS_HEADER_BLOCK_NUM: u32 = 0;
```
Comment (bobbinth) [inline store/src/genesis.rs:17]: nit: I'd probably call this just `GENESIS_BLOCK_NUM`.

**Review by bobbinth — APPROVED** [review]
Looks great! Thank you! I left one minor nit inline. After it is addressed, we can merge.

File: store/src/genesis.rs (hunk 1 above)
Comment (plafer) [reply store/src/genesis.rs]: done
