### PR TITLE
fix: Make NtxDataStore note script cache global

### LINKED ISSUE #1397: Make ntx script cache global
We have a note script cache in the NtxDataStore impl [here](https://github.com/0xMiden/miden-node/blob/next/crates/ntx-builder/src/transaction.rs#L259).

Right now the NtxDataStore is created for every transaction execution ([here](https://github.com/0xMiden/miden-node/blob/next/crates/ntx-builder/src/transaction.rs#L128)) and so is the script cache. We actually intend for the lifecycle of the script cache to be a superset of every NtxDataStore instance.

The implementation need to be changed so that the cache is instantiated outside of the NtxDataStore and fed into it. The cache should be global across all NtxDataStore instances.

### PR DESCRIPTION
**Pull request by sergerad**
## Context

Closes #1397.

## Changes

- Adds LruCache newtype
- Moves note script cache to be global across NtxDataStore instances

### CODE REVIEW

File: crates/ntx-builder/src/transaction.rs [hunk 1]
```diff
@@ -70,19 +70,45 @@ type NtxResult<T> = Result<T, NtxError>;
...
+    /// LRU cache for storing retrieved note scripts to avoid repeated store calls.
+    script_cache: Arc<Mutex<LruCache<Word, NoteScript>>>,
 }
 
 impl NtxContext {
+    /// Default cache size for note scripts.
+    ///
+    /// Each cached script contains the deserialized `NoteScript` object, so the actual memory usage
+    /// depends on the complexity of the scripts being cached.
+    const DEFAULT_SCRIPT_CACHE_SIZE: usize = 1000;
```
Comment (Mirko-von-Leipzig) [inline crates/ntx-builder/src/transaction.rs]: I believe you can move the non-zero check here to compile time


```suggestion
    const DEFAULT_SCRIPT_CACHE_SIZE: NonZeroUsize = NonZeroUsize::new(1_000).unwrap();
```

File: crates/ntx-builder/src/transaction.rs [hunk 2]
```diff
@@ -70,19 +70,45 @@ type NtxResult<T> = Result<T, NtxError>;
...
     /// computationally intensive.
-    pub prover: Option<RemoteTransactionProver>,
+    prover: Option<RemoteTransactionProver>,
 
     /// The store client for retrieving note scripts.
-    pub store: StoreClient,
+    store: StoreClient,
+
+    /// LRU cache for storing retrieved note scripts to avoid repeated store calls.
+    script_cache: Arc<Mutex<LruCache<Word, NoteScript>>>,
```
Comment (Mirko-von-Leipzig) [inline crates/ntx-builder/src/transaction.rs]: We should consider creating `struct ScriptCache` because this contains a `tokio::Mutex` which is dangerous if held across an await point. Which can happen by accident rather quickly.

So I'm thinking we move the mutex access inside the struct where we can easily audit and control the lock guard.

e.g.

```rust
#[derive(Clone, Default)]
struct ScriptCache(Arc<Mutex<LruCache<Word, NoteScript>>>);

impl ScriptCache {
    pub fn get(&self, script: Word) -> Option<NoteScript> {
        ...
    }

    pub fn put(&mut self, root: Word, script: NoteScript) {
        ...
    }
}
```

Comment (Mirko-von-Leipzig) [reply crates/ntx-builder/src/transaction.rs]: Although you can probably argue that this is _only_ used by the data store impl and therefore its already quite constrained in scope. Feel free to ignore this suggestion, but then I would recommend we add some warning comments to the data store impl.

Comment (bobbinth) [reply crates/ntx-builder/src/transaction.rs]: I'd be in favor of adding `struct ScriptCache` (or maybe `NoteScriptCache`) newtype as I think it will improve the readability for very little cost.

**Review by bobbinth — APPROVED** [review]
Looks good! Thank you!

File: crates/ntx-builder/src/transaction.rs (hunk 2 above)
Comment (sergerad) [reply crates/ntx-builder/src/transaction.rs]: I made it generic and just called it `LruCache<K, V>`

File: crates/utils/src/lru_cache.rs [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+{
+    /// Creates a new cache with the given capacity.
+    pub fn new(capacity: NonZeroUsize) -> Self {
+        Self(Arc::new(Mutex::new(InnerCache::new(capacity))))
+    }
+
+    /// Retrieves a value from the cache.
+    pub async fn get(&self, key: &K) -> Option<V> {
+        let mut cache_guard = self.0.lock().await;
+        cache_guard.get(key).cloned()
```
Comment (Mirko-von-Leipzig) [inline crates/utils/src/lru_cache.rs]: Nit

```suggestion
        self.0.lock().await.get(key).cloned()
```

File: crates/utils/src/lru_cache.rs [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+    }
+
+    /// Puts a value into the cache.
+    pub async fn put(&mut self, key: K, value: V) {
+        let mut cache_guard = self.0.lock().await;
+        cache_guard.put(key, value);
```
Comment (Mirko-von-Leipzig) [inline crates/utils/src/lru_cache.rs]:
```suggestion
        self.0.lock().await.put(key, value);
```

File: crates/ntx-builder/src/transaction.rs (hunk 2 above)
Comment (drahnr) [reply crates/ntx-builder/src/transaction.rs]: A `tokio::sync::Mutex` would actually be fine, an `std::sync::Mutex`, not so much: https://docs.rs/tokio/latest/tokio/sync/struct.Mutex.html#which-kind-of-mutex-should-you-use

Comment (Mirko-von-Leipzig) [reply crates/ntx-builder/src/transaction.rs]: Ah misremembered :grin:

File: crates/ntx-builder/src/transaction.rs [hunk 5]
```diff
@@ -70,19 +69,42 @@ type NtxResult<T> = Result<T, NtxError>;
...
+    /// LRU cache for storing retrieved note scripts to avoid repeated store calls.
+    script_cache: LruCache<Word, NoteScript>,
 }
 
 impl NtxContext {
+    /// Default cache size for note scripts.
+    ///
+    /// Each cached script contains the deserialized `NoteScript` object, so the actual memory usage
+    /// depends on the complexity of the scripts being cached.
+    const DEFAULT_SCRIPT_CACHE_SIZE: NonZeroUsize = NonZeroUsize::new(1000).unwrap();
```
Comment (bobbinth) [inline crates/ntx-builder/src/transaction.rs:92]: Eventually, we should make this limit configurable. Let's create an issue for this (unless we already have one)
