### PR TITLE
fix: handle txs from network account in ntx builder

### LINKED ISSUE #1527: Fix: network transactions in network monitor.
Currently, the network monitor is experiencing several issues related to network transactions:

---

## 1. Crash on fresh monitor + node startup (Fixed)

If you start a fresh network monitor together with a fresh node, the network monitor crashes with the following error:

```
  Error: Failed to submit proven transaction to RPC
  
  Caused by:
      status: 'Client specified an invalid argument', self: "Invalid transaction: \ncaused by: failed to re-executed the transaction\ncaused by: failed to fetch asset witnesses from the data store\ncaused by: failed to open vault\ncaused by: asset is not tracked in the partial vault\ncaused by: partial smt does not track the merkle path for key 0x0000000000000000000000000000000000c59ef76a63fe59201bf5d244f09e5c", metadata: {"content-type": "application/grpc", "date": "Fri, 16 Jan 2026 20:33:47 GMT", "access-control-expose-headers": "grpc-status,grpc-message,grpc-status-details-bin", "access-control-allow-credentials": "true", "vary": "origin, access-control-request-method, access-control-request-headers"}
```

This is fixed by updating the validator’s `DataStore::get_vault_asset_witnesses` implementation to always return an empty vector.

The fix is included in https://github.com/0xMiden/miden-node/pull/1526 .

## 2. Block validation failure after counter increment request (Fixed)

After applying the fix above, the following error appears when sending a counter increment request from the network monitor:

```
2026-01-16T20:37:07.033735Z  INFO block_builder.build_block:block_builder.propose_block: miden-block-producer: crates/block-producer/src/block_builder/mod.rs:238: close, time.busy: 88.2µs, time.idle: 2.04µs
2026-01-16T20:37:07.034656Z ERROR rpc: tower_http::trace::on_failure: /Users/spittella/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tower-http-0.6.8/src/trace/on_failure.rs:93: response failed, classification: Code: 3, latency: 0 ms rpc.service: "validator.Api", rpc.method: "SignBlock", otel.name: "validator.Api/SignBlock"
2026-01-16T20:37:07.034679Z  INFO rpc: miden_node_utils::tracing::grpc: crates/utils/src/tracing/grpc.rs:21: close, time.busy: 625µs, time.idle: 13.5µs rpc.service: "validator.Api", rpc.method: "SignBlock", otel.name: "validator.Api/SignBlock"
2026-01-16T20:37:07.034806Z ERROR block_builder.build_block:block_builder.validate_block:validator.client.validate_block: miden-block-producer: crates/block-producer/src/validator/mod.rs:50: error: gRPC transport error: status: 'Client specified an invalid argument', self: "Failed to validate block: transaction 0x999b842f3eab412bf69a21d67df9f3c4bcd0563a72e6074e1781b34d4af85799 in block 6 has not been validated", metadata: {"content-type": "application/grpc", "date": "Fri, 16 Jan 2026 20:37:07 GMT"}
2026-01-16T20:37:07.034825Z  INFO block_builder.build_block:block_builder.validate_block:validator.client.validate_block: miden-block-producer: crates/block-producer/src/validator/mod.rs:50: close, time.busy: 174µs, time.idle: 890µs
2026-01-16T20:37:07.034836Z ERROR block_builder.build_block:block_builder.validate_block: miden-block-producer: crates/block-producer/src/block_builder/mod.rs:252: error: failed to validate block
```

This appears to be caused by a merge conflict that was not handled correctly and rolled back the `transaction_inputs` addition for the counter increment transaction.

This is also fixed in https://github.com/0xMiden/miden-node/pull/1526 .

The solution was to re-add the transaction inputs to the request payload.

## 3. Counter stops incrementing after the first success (WIP)

This is still a work in progress.

With the fixes above in place, the network monitor successfully sends counter increment requests and the transactions are accepted. The first counter increment transaction succeeds, but after that the counter is never incremented again, and missing increments start to accumulate (see image below).

Image

I’m not sure what’s causing this last issue. Any ideas or pointers would be appreciated 😅

### PR DESCRIPTION
**Pull request by SantiagoPittella**
closes #1527

### CODE REVIEW

File: crates/ntx-builder/src/actor/account_state.rs [hunk 1]
```diff
@@ -214,10 +214,10 @@ impl NetworkAccountState {
                 match update {
                     NetworkAccountEffect::Updated(account_delta) => {
                         self.account.add_delta(&account_delta);
+                        tx_impact.account_delta = Some(account_prefix);
```
Comment (igamigo) [inline crates/ntx-builder/src/actor/account_state.rs:217]: Not from this PR, but this being named `tx_impact.account_delta` seems a bit misleading. Not sure what a good replacement for it would be though.

Also would it make sense to add the delta to `TransactionImpact`? Something like 

```rust
                match update {
                    NetworkAccountEffect::Updated(account_delta) => {
                        self.account.add_delta(&account_delta);
                    },
                    NetworkAccountEffect::Created(acc) => {
                         self.account.add_delta(acc.try_into()?);
                    },
                }
                tx_impact.account_delta = Some(account_prefix);

```

I guess if it works as it is in your PR, it's fine, but I guess I'm mostly wondering why creation does not require a delta.

**Review by igamigo — APPROVED** [review]
LGTM! Glad this worked.

File: crates/ntx-builder/src/actor/account_state.rs (hunk 1 above)
Comment (SantiagoPittella) [reply crates/ntx-builder/src/actor/account_state.rs:217]: I couldn;t find a way to go from `Account` -> `AccountDelta` 🤔

Comment (SantiagoPittella) [reply crates/ntx-builder/src/actor/account_state.rs:217]: Found it! Though new accounts have seed and the casting method errors in that case

Comment (igamigo) [reply crates/ntx-builder/src/actor/account_state.rs:217]: Makes sense

**Review by sergerad — APPROVED** [review]

File: crates/ntx-builder/src/coordinator.rs [hunk 2]
```diff
@@ -229,7 +230,19 @@ impl Coordinator {
         event: &Arc<MempoolEvent>,
     ) -> Result<(), SendError<Arc<MempoolEvent>>> {
         let mut target_actors = HashMap::new();
-        if let MempoolEvent::TransactionAdded { id, network_notes, .. } = event.as_ref() {
+        if let MempoolEvent::TransactionAdded { id, network_notes, account_delta, .. } =
+            event.as_ref()
+        {
+            if let Some(AccountUpdateDetails::Delta(delta)) = account_delta {
```
Comment (bobbinth) [inline crates/ntx-builder/src/coordinator.rs:239]: Could we add a brief comment explaining what it does? My understanding is that her we also want to send the transaction to the account against which the transaction is executed (assuming it is a network account), right?

**Review by bobbinth — APPROVED** [review]
Looks good! Thank you! I left one small comment inline.

File: crates/ntx-builder/src/coordinator.rs (hunk 2 above)
Comment (Mirko-von-Leipzig) [reply crates/ntx-builder/src/coordinator.rs:239]: That's correct. This is how an actor finds out if its own transaction succeeded or failed, or if someone external updated the account (which is not allowed yet).
