### PR TITLE
fix: predefine otel.name field with empty value

### LINKED ISSUE #1263: gRPC span names aren't working
#1206 simplified the gRPC span names by using `otel.name = <span-name>` which in theory allows us to specify a dynamic span name for open-telemetry purposes. `tracing` does not support dynamic span names, only string literals.

Unfortunately we're not seeing these span names arrive in our honeycomb backend; instead the `tracing` placeholder `grpc_method` root span name is there. This seems to indicate that our `otel.name` solution isn't working even though the [documentation](https://docs.rs/tracing-opentelemetry/latest/tracing_opentelemetry/index.html#special-fields) and issues indicate that it should.

Having this functionality work properly is quite essential to our monitoring so we need to figure this out.

I suggest investigating this by creating a small stand-alone binary and hooking it up to some otel collector to see the span name. i.e. create a span using tracing and then override it with `otel.name` and check that the collector actually see's this and the proceed from there.

I believe otel has a stdout logger type collector as well, which I imagine should do the right thing™️. Alternatively, hooking it up to jaeger or some other external otel compatible backend should also suffice.

### PR DESCRIPTION
**Pull request by SantiagoPittella**
fixes #1263

### CODE REVIEW

File: crates/utils/src/tracing/grpc.rs [hunk 1]
```diff
@@ -8,8 +10,22 @@ use crate::tracing::OpenTelemetrySpanExt;
 /// Additionally also pulls in remote tracing context which allows the server trace to be connected
 /// to the client's origin trace.
 pub fn grpc_trace_fn<T>(request: &http::Request<T>) -> tracing::Span {
-    // Create a span with a generic, static name.
-    let span = tracing::info_span!("rpc", rpc.uri = %request.uri());
+    // Create a span with a generic, static name. Fields to be recorded after needs to be
+    // initialized as empty since otherwise the assignment will have no effect.
+    let span = tracing::info_span!("rpc", rpc.uri = %request.uri(), otel.name = field::Empty);
```
Comment (Mirko-von-Leipzig) [inline crates/utils/src/tracing/grpc.rs]: Let's also preset the `rpc.service` and `rpc.method` fields like this? aka 

`span.record("rpc.service, service);`

Comment (sergerad) [reply crates/utils/src/tracing/grpc.rs]: Feel free to revert my commit that replaced that logic with the simple uri. I used it to debug on devnet, not required anymore

Comment (sergerad) [reply crates/utils/src/tracing/grpc.rs]: (as in we don't need to have the uri field anymore) I see the service/method logic is below here
